# Generated by Django 2.2.6 on 2021-10-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraperdatabase', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Film',
        ),
    ]
